-- Temporary RLS Disable for Testing
-- Run this in your Supabase SQL Editor to temporarily disable RLS

-- Disable RLS on all tables temporarily for testing
ALTER TABLE events DISABLE ROW LEVEL SECURITY;
ALTER TABLE workshops DISABLE ROW LEVEL SECURITY;
ALTER TABLE projects DISABLE ROW LEVEL SECURITY;
ALTER TABLE resources DISABLE ROW LEVEL SECURITY;
ALTER TABLE profiles DISABLE ROW LEVEL SECURITY;
ALTER TABLE notifications DISABLE ROW LEVEL SECURITY;
ALTER TABLE activities DISABLE ROW LEVEL SECURITY;
ALTER TABLE leetcode_progress DISABLE ROW LEVEL SECURITY;
ALTER TABLE leetcode_user_stats DISABLE ROW LEVEL SECURITY;

-- To re-enable RLS later, run:
/*
ALTER TABLE events ENABLE ROW LEVEL SECURITY;
ALTER TABLE workshops ENABLE ROW LEVEL SECURITY;
ALTER TABLE projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE resources ENABLE ROW LEVEL SECURITY;
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE notifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE activities ENABLE ROW LEVEL SECURITY;
ALTER TABLE leetcode_progress ENABLE ROW LEVEL SECURITY;
ALTER TABLE leetcode_user_stats ENABLE ROW LEVEL SECURITY;
*/ 
-- Run this in your Supabase SQL Editor to temporarily disable RLS

-- Disable RLS on all tables temporarily for testing
ALTER TABLE events DISABLE ROW LEVEL SECURITY;
ALTER TABLE workshops DISABLE ROW LEVEL SECURITY;
ALTER TABLE projects DISABLE ROW LEVEL SECURITY;
ALTER TABLE resources DISABLE ROW LEVEL SECURITY;
ALTER TABLE profiles DISABLE ROW LEVEL SECURITY;
ALTER TABLE notifications DISABLE ROW LEVEL SECURITY;
ALTER TABLE activities DISABLE ROW LEVEL SECURITY;
ALTER TABLE leetcode_progress DISABLE ROW LEVEL SECURITY;
ALTER TABLE leetcode_user_stats DISABLE ROW LEVEL SECURITY;

-- To re-enable RLS later, run:
/*
ALTER TABLE events ENABLE ROW LEVEL SECURITY;
ALTER TABLE workshops ENABLE ROW LEVEL SECURITY;
ALTER TABLE projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE resources ENABLE ROW LEVEL SECURITY;
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE notifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE activities ENABLE ROW LEVEL SECURITY;
ALTER TABLE leetcode_progress ENABLE ROW LEVEL SECURITY;
ALTER TABLE leetcode_user_stats ENABLE ROW LEVEL SECURITY;
*/ 